version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    user: vscode
    environment:
      TZ: Asisa/Tokyo
    volumes:
      - .:/workspace:cached
    command: /bin/bash
    tty: true